### ISSUE TITLE
No treasure map limit

### ISSUE THREAD

**Issue by Libreh** [NerjalNosk/bettermaps#1]
When right clicking the empty map you get an actual buried treasure map (intentional)
If you right click again while already having one, you get another, thereby you can get infinite buried treasure maps although they're all the same (I assume this is unintentional)
Maybe the player shouldn't be able to get new buried treasure maps upon right clicking if they already have one in their inventory?

**Comment by NerjalNosk** [comment]
If you are doing this in creative, this behavior is totally normal.
But unless you're using the very first version of the mod, iirc I've patched this (if not even before the first release) ; so if you're not using the latest version of the mod I'd recommend you to do so, and try again. Otherwise, I'd gladly take in some logs to see what may be going wrong.

**Comment by Libreh** [comment]
Ok, it was just me being in creative, it works as expected in survival.
I didn't realize that creative acts this way, but the more you know I guess

**Comment by NerjalNosk** [comment]
I actually only designed it after the way empty maps work in vanilla. In the end, glad it isn't an actual error ^^
