### ISSUE TITLE
Update to 1.20.5 and 1.20.6

### ISSUE THREAD

**Issue by DearFox** [NerjalNosk/bettermaps#4]
This mod seems to be simply necessary for the game.  Correct me if this bug was fixed in the vanilla game, but I haven't heard about it.

**Comment by NerjalNosk** [comment]
Afaik the vanilla issue is not a bug, but rather a design flaw.
I am still considering whether to work on 1.20.5 and 1.20.6 or purely wait for 1.21, I tend to much prefer working on major releases than sub versions (also because Mojang has decided to make all their breaking changes in minor versions, which makes it a real pain to follow through)

**Comment by HatTrkPatrk** [comment]
> Afaik the vanilla issue is not a bug, but rather a design flaw. I am still considering whether to work on 1.20.5 and 1.20.6 or purely wait for 1.21, I tend to much prefer working on major releases than sub versions (also because Mojang has decided to make all their breaking changes in minor versions, which makes it a real pain to follow through)

Do you still plan to update this to 1.21?

**Comment by NerjalNosk** [comment]
Yes. I only have other priorities on the modding department, but it will come, possibly pretty soon even.

**Comment by AlphaLeoli** [comment]
now when 🗿

**Comment by NerjalNosk** [comment]
Have actually been working on it, but I have to work out something else beforehand

**Comment by NerjalNosk** [comment]
Done and released on [Modrinth](https://modrinth.com/mod/bettermaps/version/0.6.0-beta)
